FROM node:6.2.2

RUN npm install -g yarn
RUN yarn global add nodemon

COPY ./package.json /src/package.json
COPY ./yarn.lock /src/yarn.lock

RUN cd /src && yarn install

COPY . /src

WORKDIR /src

CMD ["nodemon", "-L", "-e", "js,sql,ejs,html", "run", "start-dev"]
