FROM node:6.2.2

RUN npm install -g yarn
RUN yarn install -g nodemon

COPY ./package.json /src/package.json
RUN cd /src && yarn install

COPY . /src

WORKDIR /src

CMD ["nodemon", "-L", "-e", "js,sql,ejs,html", "run", "start-dev"]
